version: '3.2'

services:
  elasticsearch:
    restart: on-failure
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-changeme}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    restart: on-failure
    container_name: logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    expose:
      - "8080"
      - "9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      LOGSTASH_PASSWORD: ${LOGSTASH_PASSWORD:-changeme}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-changeme}
      LOGSTASH_HTTP_USERNAME: ${LOGSTASH_HTTP_USERNAME:-changeme}
      LOGSTASH_HTTP_PASSWORD: ${LOGSTASH_HTTP_PASSWORD:-changeme}
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    restart: on-failure
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    expose:
      - "5601"
    environment:
        KIBANA_PASSWORD: ${KIBANA_PASSWORD:-changeme}
    networks:
      - elk
    depends_on:
      - elasticsearch

  letsencrypt:
    restart: unless-stopped
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Vancouver
        - URL=${DOMAIN_NAME:-freshworks.club}
        - SUBDOMAINS=${SUBDOMAIN_LIST:-elk.th,}
        - ONLY_SUBDOMAINS=true
        - VALIDATION=http
    volumes:
        - type: volume
          source: letsencrypt-config
          target: /config
        - type: bind
          source: ./nginx/site-confs/logstash.conf
          target: /config/nginx/site-confs/logstash.conf
        - type: bind
          source: ./nginx/site-confs/kibana.conf
          target: /config/nginx/site-confs/kibana.conf
        - type: bind
          source: ./nginx/nginx.conf
          target: /config/nginx/nginx.conf
    networks:
        - elk
    ports:
        - 443:443
        - 80:80
        - 5601:5601
        - 9200:9200
        - 8080:8080

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  letsencrypt-config:
